# Generated by Django 5.2 on 2025-04-24 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nationalpark',
            name='area_in_acres',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nationalpark',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='nationalpark',
            name='established_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nationalpark',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='nationalpark',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='UserParkInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('activities', models.TextField(blank=True)),
                ('rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('visited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_infos', to='main_app.nationalpark')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'park')},
            },
        ),
    ]
