# Generated by Django 5.2 on 2025-04-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_nationalpark_area_in_acres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationalpark',
            name='photo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userparkinfo',
            name='user_photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos/'),
        ),
    ]
