# Generated by Django 5.2 on 2025-04-25 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_nationalpark_photo_url_userparkinfo_user_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='main_app.nationalpark')),
            ],
        ),
    ]
