# Generated by Django 5.2 on 2025-04-25 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_parkphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nationalpark',
            name='area_in_acres',
        ),
        migrations.RemoveField(
            model_name='nationalpark',
            name='established_date',
        ),
    ]
