# Generated by Django 5.2 on 2025-04-26 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_nationalpark_area_in_acres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userparkinfo',
            name='chosen_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.parkphoto'),
        ),
    ]
