# Generated by Django 5.2 on 2025-04-27 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_userparkinfo_chosen_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userparkinfo',
            name='user_photo',
        ),
    ]
