# Generated by Django 5.2 on 2025-04-27 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_userparkinfo_user_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user_photos/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('user_park_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_photos', to='main_app.userparkinfo')),
            ],
        ),
    ]
